name: CI
on:
  push:
    branches:
      - 'master'
  pull_request: {}
  
jobs:
  test:
    strategy:
      matrix:
        node-version: [16]
        os: ['ubuntu-latest']
    runs-on: ${{ matrix.os }}
    env: 
      Hello: ${{ secrets.Hello }}
    steps:
      - uses: actions/checkout@v2
      - name: use Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: test
        run: |
          if ["$Hello" -eq "bae"]
          then 
            echo "Got you secret"
          fi
      