name: CI
on:
  push:
    branches:
      - 'master'
  pull_request: {}

jobs:
  test:
    strategy:
      matrix:
        node-version: [16]
        os: ['ubuntu-latest']
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: use Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: install
        run: npm install
      - name: postinstall 
        run: cd api && npm install
      - name: server-1-install
        run: cd server-1 && npm install
      - name: server-2-install
        run: cd server-2 && npm install 
      - name: launch-servers
        run: node server-1/index.js && node server-2/index.js
      - name: test
        run: cd api && npm run CI